export const locationIdeaList = [
	'Desert',
	'Cave',
	'Abandoned Manor',
	'Ancient Graveyard',
	'Ruined Castle',
	'Forgotten Battlefield',
	'Cursed Woods',
	'Secluded Crypts',
	'Desolate Moor',
	'Cliffside by the Sea',
	'Ruins of a Monastery',
	'Mage’s Tower',
	'Floating Islands in the Sky',
	'Underwater City Ruins',
	'Volcanic Caverns of Fire Elementals',
	'Enchanted Forest of Talking Trees',
	'Ice Fortress in a Glacial Crevasse',
	'Hidden Valley of Dinosaurs',
	'Labyrinthine Library of Forbidden Knowledge',
	'City in the Clouds',
	'Ancient Observatory on a Remote Mountain Peak',
	'Subterranean Kingdom of the Mole People',
	'Eternal Nightfall City',
	'Sunken Ruins of an Ancient City',
	'Dimensional Crossroads',
	'The Shifting Sands of the Timeless Desert',
	'Crystal Caves of the Mind Flayers',
	'The Great Library of All Knowledge',
	'Sky Pirates’ Airship Haven',
	'Portal Nexus under Siege',
	'The Forgotten Temple of the Moon',
	'Spectral Shipwreck at the Ocean’s Abyss',
	'The Lost Gardens of the Feywild',
	'The Petrified Forest of Statues',
	'The Collapsing Towers of the Arcane',
	'The Hollow Earth’s Inner World',
	'The Mirror City of Reflections',
	'The Eternal Glacier with Hidden Life',
	'Corrupted Swamp with Acidic Pools',
	'Decayed Forest Overrun by Blight',
	'Abandoned Castle Shrouded in Dark Magic',
	'Deep Caverns Beneath a Dead Mountain',
	'Marshland Fortress Wrapped in Mists',
	'Ruined Temple Sunk Beneath Murky Waters',
	'Abandoned Mine Shafts',
	'Underground Sewer Systems',
	'Ancient Ruined Catacombs',
	'Dank Dungeons Beneath Old Castles',
	'Natural Caves Filled with Stalactites and Stalagmites',
	'Derelict Ships Sunk in Dark Waters',
	'Forgotten Subterranean Temples',
	'Deep Chasms in the Earth',
	'The Depths of a Haunted Forest',
	'Lost Cities Swallowed by the Earth',
	'Enchanted Glade Cursed by a Covetous King',
	'Ancient Grove Where a Treacherous Deal Was Struck',
	'Sacred Pool Tainted by Thieves’ Blood',
	'Ruins of a Temple Defiled by Greed',
	'Ghostly Forest, Site of a Massacre Over Forgotten Gold',
	'Mountain Pass Guarded by Spirits of Fallen Nature Protectors',
	'Crystal Lake Reflecting the Greed of Those Who Gaze Upon It',
	'Valley of Whispering Winds, Where Echoes Speak of Betrayal',
	'Misty Highlands Shrouded in the Sorrow of a Greedy Clan’s Demise',
	'Blighted Orchard That Once Flourished Until Stricken by Avarice',
	'Ancient Desert Palace Buried by Sand',
	'Rocky Plateau Overlooking Vast Drylands',
	'Grand Canyon with Hidden Caves and Passages',
	'Ruined Fortress in a Desert Oasis, Now Dry',
	'Sphinx-guarded Tomb in the Heart of the Desert',
	'Cliffside Aerie in a Barren Mountain Range',
	'Abandoned City at the Edge of a Desert, Taken Over by Sand',
	'Massive, Petrified Forest in a Desert, Home to Lost Treasures',
	'Deep Chasm in a Dry Riverbed, Concealing an Underground Palace',
	"Dried-up Lakebed, with the Dragon's Lair in the Ancient Lake's Depths",
	'Dense Forests with Thick Underbrush',
	'Muddy Riverbanks Rich in Vegetation',
	'Overgrown Ruins Reclaimed by Nature',
	'Mystical Glades with Magical Properties',
	'Foothills Leading to Mountainous Terrains',
	'Borderlands Between Civilized Farms and Wild Woods',
	'Ancient Druid Groves Sacred to Nature Deities',
	'Swamps with Dense Canopies and Sunlight Patches',
	'Bramble-Thicketed Clearings in Deep Woods',
	'Abandoned Orchards Gone Wild and Overgrown',
	'Abandoned Jewelry Maker’s Shop, cluttered with trinkets and baubles',
	'Overgrown Hedge Maze with hidden treasures and traps',
	'Old, Forgotten Wells, rumored to be filled with wishes and coins',
	'Dilapidated Mansions, where generations of hidden wealth lie scattered',
	'Ruined Castles with treasure vaults that have been long since looted',
	'Enchanted Forest Clearings, known for strange and luminous objects',
	'Ancient Crossroads, where travelers have lost precious items',
	'Cave Systems beneath Old Market Towns, littered with lost possessions',
	'Attics of Haunted Houses, where forgotten heirlooms gather dust',
	'The Wreckage of Sunken Ships, where the boggarts collect drowned treasures',
	"Necromancer's Tower, hidden deep within a cursed forest",
	'Ancient Crypts beneath a long-forgotten battlefield',
	'Ruined Temples dedicated to gods of death and the underworld',
	'Forbidden Libraries containing dark magical tomes',
	"Sorcerer's Laboratory, where arcane experiments went awry",
	'Catacombs under an ancient city, lined with the bones of the past',
	'Dark Mausoleums in a graveyard where the veil is thin',
	'Abandoned Castles where dark rituals were once performed',
	'Desecrated Shrines once sacred, now home to dark forces',
	'Lost Dungeons beneath a cursed land, forgotten by time',
	'Ancient Forge of a God of Craftsmanship, hidden within a mountain',
	'Ruins of a Great Library that once held the knowledge of metalwork and magic',
	'Hall of Heroes, where statues of great warriors and smiths come to life',
	'Abandoned City of Dwarves, known for their metalworking and engineering',
	'Mystical Foundry, where magical weapons were once forged',
	'The Vault of a Long-Lost Civilization, protected by these metallic guardians',
	'Arcane Workshop of a Legendary Artificer, filled with unfinished constructs',
	'Deserted Palace Courtyard, where the constructs serve as eternal sentinels',
	'Temple to a Deity of Fire and Forging, where the constructs are worshippers',
	'Secret Chamber within an Alchemist’s Tower, where experiments on metal and fire converge',
	'Dense Forests with hidden trails and ambush spots',
	'Cave Systems serving as hideouts and bases for raiding nearby settlements',
	'Ruined Fortresses repurposed as strongholds for their bands',
	'Abandoned Mines, using the tunnels for surprise attacks',
	'Mountain Passes, controlling strategic routes for tolls and ambushes',
	'Thick Swamps, utilizing the difficult terrain to evade pursuit',
	'Derelict Buildings on the outskirts of civilization, serving as forward bases',
	'Undercity Sewers, exploiting the labyrinthine passages for raids into urban areas',
	'Old Watchtowers, converted into lookout points for regional dominance',
	'Hidden Glens within forests, serving as camps and meeting points for multiple bands',
	'Fallow Fields - Once fertile farmland, now abandoned and full of easy prey for the horror.',
	'Ancient Battlefields - Rich in the remains of fallen warriors, providing both cover and sustenance.',
	'Decayed Forests - Where thick roots provide nourishment and the dense canopy helps conceal movements.',
	'Ruined Outposts - Areas where civilization once encroached upon nature, now a hunting ground.',
	'Deserted Quarries - Deep pits and loose soil make for perfect burrowing terrain.',
	'Eroded Canyons - The layered earth of these regions allows for complex tunneling.',
	'Marshlands - Soft ground and abundant life make these areas ideal for lurking horrors.',
	'Old Graveyards - Rich in decomposed matter, providing both a hunting ground and camouflage.',
	'Collapsed Mines - Offering a network of pre-dug tunnels to expand and hunt within.',
	'Forsaken Villages - Abandoned places where these horrors can roam freely beneath the unkempt grounds.',
	'Murky Swamplands - Dense fog and thick vegetation obscure the creature, making its deadly gaze a surprise.',
	"Petrified Forests - Trees turned to stone hint at the catoblepas's presence, a grim warning for travelers.",
	"Cursed Marshes - Lands blighted by dark magic, where the catoblepas's paralyzing gaze adds to the desolation.",
	'Ancient Ruins by Water - Structures half-sunken into swamps or lakes, where catoblepas lurk, blending history with horror.',
	'Fetid Lagoons - Stagnant, poison-filled waters that are home to these monstrosities, deterring most life forms.',
	'Blighted Farmland - Once fertile lands, now withered and dying, patrolled by a catoblepas feeding on the decay.',
	'Forsaken Graveyards - Where the thin veil between life and death attracts the catoblepas, a guardian of the dead.',
	"Mystical Glades - Rare, hidden places where moonlight has strong magical properties, offering a cure to the catoblepas's stone curse.",
	'Boundary of Realms - Regions where the material plane brushes against darker worlds, a catoblepas guarding the threshold.',
	'The Bog of Eternal Stench - A place so vile and odorous that only creatures like the catoblepas can endure its fumes.',
	'Limestone Caverns - Vast networks of caves known for their stark, white stone walls, where locusts blend perfectly.',
	'Underground Jungles - Rare ecosystems deep within the earth, where sunlight filters through cracks above, supporting lush plant life.',
	'Fungal Forests - Subterranean areas overrun with giant mushrooms and other fungi, providing ample food for the locusts.',
	'Ancient Dwarven Mines - Abandoned mining tunnels that have been reclaimed by nature, with mosses and lichens covering the walls.',
	'Crystal Caves - Sparkling caves filled with quartz and other minerals, where locusts’ coloration mimics the reflective surfaces.',
	'Druidic Sanctuaries - Sacred places below the earth where magic promotes the growth of plants, attracting hungry locusts.',
	'Ruined Underground Cities - Once bustling settlements now fallen into decay, where overgrown vegetation provides food.',
	'Subterranean Riverbanks - Moist environments where diverse plant life thrives along the water’s edge, ideal for locusts.',
	'Volcanic Vents - Caves warmed by geothermal heat, supporting unique ecosystems where these creatures can find their niche.',
	"Echoing Canyons Below - Deep fissures in the earth that open into wider cave systems, where the locusts' shrieks reverberate.",
	'Verdant Meadows - Expansive grasslands where centaur herds can roam freely and graze.',
	'Sacred Groves - Forested areas considered holy, where centaurs gather for rituals and to commune with nature.',
	'Borderlands - The outskirts of forests and human settlements, where centaurs might interact or conflict with other races.',
	'Ancient Ruins in the Wild - Remnants of old civilizations in natural settings, where centaurs may establish homes or hold gatherings.',
	'Riverbanks and Lakesides - Fertile and water-rich areas that support the flora and fauna centaurs rely on for sustenance.',
	'Hidden Valleys - Secluded and protected by natural formations, these valleys serve as safe havens for centaur tribes.',
	'Mountain Foothills - Regions where the terrain begins to rise, offering strategic locations for centaur outposts or villages.',
	'Mystical Clearings - Places of power within forests or plains, where centaurs perform their rites and celebrate their culture.',
	'Abandoned Vineyards - Once-cultivated lands that have gone wild, where centaurs might find both food and shelter.',
	'Crossroads in the Wilderness - Meeting points for various paths and trails, often used by centaurs as places of trade or parley with other creatures.',
	'High Mountain Peaks - Inaccessible except by flight, perfect for a lair and hunting grounds.',
	'Volcanic Caves - Reflecting the fiery aspect of their dragon heritage, with the heat serving as a comfort.',
	'Ruined Castles - Perched atop craggy hills, offering both a panoramic view for hunting and a majestic sense of domain.',
	'Deep Forest Clearings - Hidden away from prying eyes, where all three aspects of the chimera can thrive.',
	"Abandoned Temples - Especially those once dedicated to gods of beasts or war, now desecrated as the chimera's den.",
	'Mystical Ruins - Ancient sites charged with magical energy, attracting the chimera’s sorcerous nature.',
	'Cliffside Nests - Overlooking vast territories, allowing the chimera to survey its realm and spot incoming threats or prey.',
	'Desolate Moorlands - Wide-open spaces that are hard to traverse on foot, giving the chimera an advantage in hunting.',
	'Ancient Dragon Burial Sites - Drawing on the draconic aspect of the chimera, these sites could offer arcane power or treasures.',
	"Stormwracked Islands - Isolated and battered by elements, mirroring the chimera's tumultuous nature.",
	'Floating Castles - Held aloft by magic, drifting slowly through the clouds and secured against unwelcome visitors by powerful winds.',
	'Mountain Pinnacles - The highest peaks, where the air is thin, and the ground touches the heavens, perfect for giants who wish to look down upon the world.',
	'Skyborne Islands - Mysterious landmasses that float high above the earth, accessible only by those who can fly or know the giants’ secrets.',
	'Enchanted Valleys - Hidden among towering mountains, these valleys are shrouded in mists and perpetual cloud cover, guarded by the giants.',
	'Ancient Pillars of the Sky - Massive stone columns believed to hold up the sky, where cloud giants have carved out their majestic homes.',
	"Giant's Eyrie - High-altitude nests, similar to those of the largest birds of prey, but scaled to the immense size of cloud giants.",
	'Celestial Bridges - Arcing constructs that span the highest mountain ranges, serving as pathways between the realms of cloud giants.',
	'Aeries in the Mist - Platforms or small fortresses that cling to the sides of cliffs, enveloped in the dense clouds that cloud giants call home.',
	'Storm Palaces - Grand edifices that exist within the heart of perpetual storms, controlled and calmed at the whim of their cloud giant masters.',
	'Heavenly Gardens - Lush, verdant expanses that exist at high altitudes, where cloud giants cultivate rare plants and magical herbs.',
	'Ancient Crypt Entrances - Guarding the sacred resting places of heroes or kings.',
	'Vaults Containing Magical Artifacts - Where powerful items are stored and protected.',
	'Doorways to Hidden Libraries - Holding ancient knowledge and forbidden lore.',
	'Entrances to Abandoned Temples - Once centers of worship, now left in ruins.',
	'Gateways to Mystic Realms - Portals located in secluded or hard-to-reach areas.',
	"Ruined Castles' Treasuries - Guarding the last remnants of fallen kingdoms.",
	'Underground Bunkers of Ancient Civilizations - Containing technological marvels lost to time.',
	'Sacred Groves - Entrances to natural spaces imbued with powerful magic.',
	'Sealed Caverns - Hiding rare minerals or the entrance to the Underdark.',
	'Tombs of Forgotten Deities - Where the remains of once-worshipped gods lie.',
	'Overgrown Ruins - Where nature has reclaimed once-busy marketplaces or residential areas, perfect for ambushes.',
	'Petrified Forests - Filled with the stone remnants of their previous victims, adding a level of caution for adventurers.',
	'Abandoned Farms - Once thriving with livestock, now left desolate with only the cockatrice stalking the fields.',
	'Cursed Graveyards - Where the dead rest uneasily, and the cockatrice adds to the dread with its presence.',
	'Forsaken Quarries - Offering plenty of hiding spots and a fitting environment for their petrifying abilities.',
	"Dense Jungles - The thick foliage and shadows allow them to stalk prey undetected until it's too late.",
	'Old Battlefields - The scattered armor and weapons of fallen soldiers provide a grim setting for an encounter.',
	'Mystical Grottos - Hidden away and imbued with ancient magic that may have given rise to such creatures.',
	'Haunted Villages - Deserted by humans due to curses or plagues, now roamed by cockatrices among the ruins.',
	'Ancient Temples - Whose lost treasures are guarded by these creatures, using their petrifying ability as the ultimate defense.',
	'Sacred Groves - Deep within the jungle, where ancient magics are strongest and the veil between worlds is thin.',
	'Hidden Temples - Dedicated to or protected by the Couatl, filled with puzzles and traps to test the worthy.',
	'Ruined Cities - Overgrown by the jungle, where the Couatl watches over lost knowledge and forgotten treasures.',
	'Crystal Caves - Radiating magical energy, serving as a nexus for ley lines and a haven for meditation and healing.',
	'High Plateaus - Surrounded by steep cliffs, accessible only by flight, where Couatls convene and council.',
	'Ancient Obelisks - Erected in their honor, marking the boundaries of their territories and places of power.',
	'Waterfall Sanctuaries - Hidden behind cascades, these serene locations are perfect for a Couatl seeking solitude or reflection.',
	'Abandoned Astronomical Observatories - Where they study the stars and celestial events, pondering the mysteries of the universe.',
	'Magical Springs - Whose waters are imbued with healing properties, guarded by the Couatl against those who would misuse them.',
	'Enchanted Isles - In the heart of vast lakes, shrouded in mist and accessible only to those led by fate or the Couatl itself.',
	'Overgrown Ruins - Where civilization has been reclaimed by nature, perfect for vines to hide and hunt.',
	'Dense Forests - Particularly in areas with thick underbrush and a canopy that blocks most of the sunlight.',
	'Walled Gardens - Abandoned and unkempt, with the vines posing as decorative plants gone wild.',
	"Jungle Pathways - Where the thick vegetation on either side is indistinguishable until it's too late.",
	'Swamp Edges - The border areas where land meets water, allowing vines to use both environments for camouflage.',
	'Old Greenhouses - Glass structures overrun by what was once cultivated vegetation, now turned deadly.',
	'Village Outskirts - Areas where the wilderness begins to encroach on human settlements.',
	'Ancient Battlegrounds - Where the nutrients from fallen soldiers have fed the vines for centuries.',
	"Riverbanks - Especially in areas where the vines can hang from overhanging trees to snatch prey from the water's edge.",
	'Mountain Passes - In regions where the vines can grow along the rocky walls, blending in with the natural moss and foliage.',
	'Sunken Cities - Ancient metropolises that have slipped beneath the waves, where Deep Ones now dwell among the ruins.',
	'Underwater Caverns - Accessible from the sea but close to the shore, serving as gateways for Deep Ones to enter the land.',
	'Coastal Trade Ports - Where Deep Ones might clandestinely surface under the cover of night to barter with select humans.',
	'Secluded Coastal Villages - Known for ancient pacts with the sea, where the lines between human and Deep One blur.',
	'Mysterious Lighthouses - Situated on rocky outcrops far from shore, rumored to be meeting points for Deep Ones and surface dwellers.',
	'Flooded Temples - Partially submerged structures dedicated to forgotten sea gods, now home to Deep One cults.',
	'Ship Graveyards - Regions of treacherous waters where sunken ships are said to be looted by Deep Ones.',
	'Isolated Islands - With hidden underwater access points, allowing Deep Ones to emerge far from the prying eyes of larger settlements.',
	'Coral Reefs - Teeming with life and color, masking the presence of Deep One scouts observing surface activity.',
	'Estuaries and River Mouths - Where fresh water meets the sea, Deep Ones may venture to explore or make contact with the land.',
	'Ancient Battlefields - Where countless warriors fell and were left unburied, now a cursed land where Draugr rise.',
	'Desecrated Tombs - Once sacred resting places that have been violated, leading the restless dead to walk again.',
	'Forsaken Graveyards - Overgrown and forgotten, where the Draugr emerge at night to haunt the living.',
	'Ruined Fortresses - Their halls once echoed with the sounds of battle, now home only to the Draugr.',
	'Shipwrecks - Particularly those resulting from pirate attacks or battles at sea, now underwater crypts for Draugr sailors.',
	'Barrows and Burial Mounds - Ancient resting places for warriors, kings, and heroes, now disturbed by dark forces.',
	'Haunted Villages - Abandoned after devastating raids, where the slain villagers rise again as Draugr.',
	'Frozen Caverns - Hidden beneath the ice, where fallen explorers and adventurers are doomed to undeath.',
	'Cursed Forests - Where battles have spilled into the woods, leaving behind the dead who rise as Draugr.',
	'Viking Longhouses - Ruins of homes where the fallen were honored, but due to neglect, have become a haven for the undead.'
];
